apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-test-ingress
  namespace: default
spec:
  dnsNames:
    - test.your.domain
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: tls-test-ingress
  usages:
    - digital signature
    - key encipherment
